name: CI to Docker Hub
on: 
  push: 
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Verification accès au repo github
        uses: actions/checkout@v2
      
      - name: Connexion a dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Configuration environnement de build docker
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Execution du build docker et push sur dockerhub
        id: docker_build
        run:  |
          docker-compose -f docker-compose.dev.yml up
         
      - name: Push sur dockerhub
        run: |
         docker-compose push
