name: CI on Docker Hub
on: 
  push: 
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Verification accès au repo github
        uses: actions/checkout@v2
      
      - name: Connexion a dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build et publication sur dockerhub
        id: docker_build
        run: |
              docker-compose -f docker-compose.dev.yml build
              docker tag gesemp_backend ${{ secrets.DOCKER_HUB_USERNAME }}/gesemp_backend
              docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gesemp_backend
     
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
