name: CI on Docker Hub
on: 
  push: 
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Verification accès au repo github
        uses: actions/checkout@v2
      
      - run: |
              docker-compose -f docker-compose.dev.yml push --build
      
      - name: Dockerization
        if: success()
        uses: manusa/actions-publish-docker@v1.1.2
        with:
          name: ${{ secrets.DOCKER_HUB_USERNAME }}/gesemp:latest
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
     
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
